walmartlabs/concord-plugins

README.md, tasks/terraform/src/main/java/com/walmartlabs/concord/plugins/terraform/Constants.java, tasks/terraform/src/main/java/com/walmartlabs/concord/plugins/terraform/actions/PlanAction.java, tasks/terraform/src/main/java/com/walmartlabs/concord/plugins/terraform/commands/PlanCommand.java, tasks/terraform/src/test/java/com/walmartlabs/concord/plugins/terraform/TerraformTaskTest.java
Added destroy argument in plan phase based on `destroy:true|false` parameter
Closes #1
=> Terraform destroy argument

tasks/terraform/README.md, tasks/terraform/src/test/java/com/walmartlabs/concord/plugins/terraform/TerraformTaskTest.java
As documented in the README.md by setting a few items in your environment
the integration test for the Terraform plugin will just run against AWS.
=> Trying to make the integration test work out of the box

tasks/confluence/pom.xml, tasks/confluence/src/main/java/com/walmartlabs/concord/plugins/confluence/ConfluenceClient.java, tasks/confluence/src/main/java/com/walmartlabs/concord/plugins/confluence/ConfluenceTaskCommon.java, tasks/confluence/src/main/java/com/walmartlabs/concord/plugins/confluence/TaskParams.java
=> confluence: proper read page content from task input parameters

tasks/git/src/main/java/com/walmartlabs/concord/plugins/git/GitHubTask.java
_Can_ be done with `getPRList` and some filtering, but repos with tons of PRs may introduce some memory concerns.
=> git: new action - getPR

tasks/ldap/src/main/java/com/walmartlabs/concord/plugins/ldap/LdapTaskCommon.java
To prevent null pointer exception
=> Null Check

tasks/gremlin/pom.xml, tasks/gremlin/src/main/java/com/walmartlabs/concord/plugins/gremlin/GremlinClient.java, tasks/gremlin/src/main/java/com/walmartlabs/concord/plugins/gremlin/GremlinClientParams.java, tasks/gremlin/src/main/java/com/walmartlabs/concord/plugins/gremlin/TaskParams.java
to solve:
```
10:07:39 [ERROR] main -> unhandled exception
java.lang.RuntimeException: User does not have permission to perform request. Here are the full error details: {results=User requires privilege for target team: TEAM_DEFAULT}
```
+ added `debug` input parameter to log request/response
=> gremlin: `teamId` input parameter to specufy team identifier

tasks/gremlin/pom.xml, tasks/gremlin/src/main/java/com/walmartlabs/concord/plugins/gremlin/AttackResult.java, tasks/gremlin/src/main/java/com/walmartlabs/concord/plugins/gremlin/GremlinClient.java, tasks/gremlin/src/main/java/com/walmartlabs/concord/plugins/gremlin/K8SAttackResult.java, tasks/gremlin/src/main/java/com/walmartlabs/concord/plugins/gremlin/NetworkAttacks.java, tasks/gremlin/src/main/java/com/walmartlabs/concord/plugins/gremlin/ResourceAttacks.java, tasks/gremlin/src/main/java/com/walmartlabs/concord/plugins/gremlin/StateAttacks.java, tasks/gremlin/src/main/java/com/walmartlabs/concord/plugins/gremlin/TaskParams.java, tasks/gremlin/src/main/java/com/walmartlabs/concord/plugins/gremlin/Utils.java
attack on deployments:
```
- task: gremlin
in:
action: cpu
...
teamId: "123123-2123123-123123"
k8s:
cluster: "us05519-vsd1"
deployments:
- "abandonedpurchasecontracts"
```
=> gremlin: support for kubernetes targets

tasks/git/src/main/java/com/walmartlabs/concord/plugins/git/GitHubTask.java
new input parameter:
`mergeMethod` - optional, string. Merge method to use. Possible values are `merge`, `squash` or `rebase`.
GITHUB API docs: https://docs.github.com/en/rest/reference/pulls#merge-a-pull-request
=> github: allows to specify mergeMethod for mergePR action

tasks/akeyless/README.md, tasks/akeyless/pom.xml, tasks/akeyless/src/test/filtered-resources/version.properties, tasks/akeyless/src/test/java/com/walmartlabs/concord/plugins/akeyless/CommonTest.java, tasks/akeyless/src/test/java/com/walmartlabs/concord/plugins/akeyless/TaskParamsImplTest.java, tasks/akeyless/src/test/java/com/walmartlabs/concord/plugins/akeyless/it/AbstractIT.java, tasks/akeyless/src/test/java/com/walmartlabs/concord/plugins/akeyless/it/CommonIT.java, tasks/akeyless/src/test/java/com/walmartlabs/concord/plugins/akeyless/it/TaskIT.java, tasks/akeyless/src/test/resources/com/walmartlabs/concord/plugins/akeyless/it/runtimeV1/concord.yml, tasks/akeyless/src/test/resources/com/walmartlabs/concord/plugins/akeyless/it/runtimeV2/concord.yml, tasks/akeyless/src/test/resources/logback-test.xml
- Added ITs for full task calls using testcontainers
- Fix Junit5 integration tests with maven failsafe plugin.
- Only changes to test code, no changes to main code
=> akeyless: testcontainers task integration tests

tasks/argocd/src/main/java/com/walmartlabs/concord/plugins/argocd/ArgoCdClient.java, tasks/argocd/src/main/java/com/walmartlabs/concord/plugins/argocd/TaskParams.java, tasks/argocd/src/main/java/com/walmartlabs/concord/plugins/argocd/TokenAuthHandler.java, tasks/argocd/src/test/java/com/walmartlabs/concord/plugins/argocd/ArgoCdClientTest.java
- Argocd Support generating individual project tokens which makes auth simpler and granular
=> Argocd Add support for jwt tokens

tasks/git/pom.xml, tasks/git/src/main/java/com/walmartlabs/concord/plugins/git/JGitClient.java
looks like current version removed from mvn repo:
```
[WARN ] GET FAILED https://repo1.maven.org/maven2/org/eclipse/mylyn/github/org.eclipse.egit.github.core/5.4.0.201906121030-r/org.eclipse.egit.github.core-5.4.0.201906121030-r.pom <> /home/concord/.m2/repository/org/eclipse/mylyn/github/org.eclipse.egit.github.core/5.4.0.201906121030-r/org.eclipse.egit.github.core-5.4.0.201906121030-r.pom, error: org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact 
```
=> git: jgit/git versions up

tasks/argocd/argocd.yml, tasks/argocd/src/main/java/com/walmartlabs/concord/plugins/argocd/ArgoCdClient.java, tasks/argocd/src/main/java/com/walmartlabs/concord/plugins/argocd/ArgoCdTask.java, tasks/argocd/src/main/java/com/walmartlabs/concord/plugins/argocd/ObjectMapper.java, tasks/argocd/src/main/java/com/walmartlabs/concord/plugins/argocd/TaskParams.java, tasks/argocd/src/main/java/com/walmartlabs/concord/plugins/argocd/TaskParamsImpl.java, tasks/argocd/src/test/java/com/walmartlabs/concord/plugins/argocd/ArgoCdClientTest.java
Updated openapi yml file with new version 2.6.3 api spec
=>  Argocd: add support for ApplicationSet create, delete, get actions

tasks/argocd/src/main/java/com/walmartlabs/concord/plugins/argocd/ArgoCdTask.java, tasks/argocd/src/main/java/com/walmartlabs/concord/plugins/argocd/RecordEvents.java, tasks/argocd/src/main/java/com/walmartlabs/concord/plugins/argocd/TaskParamsImpl.java, tasks/argocd/src/main/java/com/walmartlabs/concord/plugins/argocd/model/EventStatus.java
* Update process event data with all the user input params
* Add new events for START, COMPLETE and FAIL cases
=> Argocd: Update process event data

tasks/git/src/main/java/com/walmartlabs/concord/plugins/git/GitHubTask.java
new option: `replace` - boolean, remove all hooks with same URL, before creating new one
=> github: allow replace existing hooks

tasks/git/src/main/java/com/walmartlabs/concord/plugins/git/GitHubTask.java
```
- task: github
in:
action: "GETPRFILES"
accessToken: "..."
org: "..."
repo: "..."
prNumber: ...
out: result
```
=> github: allow get PR files

tasks/argocd/src/main/java/com/walmartlabs/concord/plugins/argocd/ArgoCdClient.java, tasks/argocd/src/main/java/com/walmartlabs/concord/plugins/argocd/ArgoCdTask.java, tasks/argocd/src/main/java/com/walmartlabs/concord/plugins/argocd/RecordEvents.java, tasks/argocd/src/main/java/com/walmartlabs/concord/plugins/argocd/TaskParams.java, tasks/argocd/src/main/java/com/walmartlabs/concord/plugins/argocd/TaskParamsImpl.java, tasks/argocd/src/test/java/com/walmartlabs/concord/plugins/argocd/ArgoCdClientTest.java
* Recoding cluster, namespace and project details for updatespec action.
* Added upsert flag for create action
=> Argocd: Update updateSpec Event data, Add upsert flag for create action

tasks/argocd/pom.xml, tasks/argocd/src/main/java/com/walmartlabs/concord/plugins/argocd/ArgoCdClient.java, tasks/argocd/src/main/java/com/walmartlabs/concord/plugins/argocd/CallRetry.java, tasks/argocd/src/test/java/com/walmartlabs/concord/plugins/argocd/ArgoCdClientIT.java, tasks/argocd/src/test/java/com/walmartlabs/concord/plugins/argocd/ArgoCdClientTest.java, tasks/argocd/src/test/java/com/walmartlabs/concord/plugins/argocd/CallRetryTest.java
Tested the changes in dev environment which has newer version of argocd(2.9.3)
=> argocd: Add retry logic for waitForSync operation to support for new version of argocd

tasks/confluence/src/main/java/com/walmartlabs/concord/plugins/confluence/ConfluenceTaskCommon.java, tasks/confluence/src/main/java/com/walmartlabs/concord/plugins/confluence/Result.java, tasks/confluence/src/main/java/com/walmartlabs/concord/plugins/confluence/TaskParams.java, tasks/confluence/src/main/java/com/walmartlabs/concord/plugins/confluence/Utils.java
Adding support for ids that exceeds Integer MAX_VALUE
=> confluence: handle page IDs as long values

tasks/gremlin/pom.xml, tasks/gremlin/src/main/java/com/walmartlabs/concord/plugins/gremlin/AttackResult.java, tasks/gremlin/src/main/java/com/walmartlabs/concord/plugins/gremlin/GremlinClient.java, tasks/gremlin/src/main/java/com/walmartlabs/concord/plugins/gremlin/K8SAttackResult.java, tasks/gremlin/src/main/java/com/walmartlabs/concord/plugins/gremlin/Utils.java
Not particularly easy to test this task :(
=> gremlin: remove okhttp and gson dependencies

pom.xml
Fixes compilation issues like https://github.com/walmartlabs/concord-plugins/pull/181#discussion_r1867045387
=> project: bump takari-lifecycle-plugin version
