- tasks/terraform/README.md
- tasks/terraform/src/test/java/com/walmartlabs/concord/plugins/terraform/TerraformTaskTest.java
The TerraformTask will now look for the standard envars that are in
the AWS docs and which most tools support:
AWS_ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY
But we will also look for the following envars not to break anyone
using them:
AWS_ACCESS_KEY
AWS_SECRET_KEY
> Terraform: Adding support for the standard AWS envars

- tasks/terraform/src/main/java/com/walmartlabs/concord/plugins/terraform/TerraformTask.java
- tasks/terraform/src/main/java/com/walmartlabs/concord/plugins/terraform/backend/BackendManager.java
- tasks/terraform/src/main/java/com/walmartlabs/concord/plugins/terraform/backend/SupportedBackend.java
- tasks/terraform/src/test/java/com/walmartlabs/concord/plugins/terraform/TerraformTaskTest.java
- tasks/terraform/src/test/java/com/walmartlabs/concord/plugins/terraform/backend/BackendManagerTest.java
- Created BackendManager to encapsulate the creation and validation of Backends
- Created BackendManagerTest to make sure
- Unsupported backends are rejected upfront
- Only one backend can be configured
- Reworked the TerraformTaskTest to use the BackendManager
> Refactor backend management to improve general support

- tasks/s3/src/main/java/com/walmartlabs/concord/plugins/s3/Constants.java
- tasks/s3/src/main/java/com/walmartlabs/concord/plugins/s3/S3Task.java
This change allows the user to specify a dst for the path in the workspace where the
retrieved object will be place, and if not specified defaults to the object key
> Allow the specification of the local path for the retrieve object

- tasks/terraform/src/main/java/com/walmartlabs/concord/plugins/terraform/Constants.java
- tasks/terraform/src/main/java/com/walmartlabs/concord/plugins/terraform/Terraform.java
- tasks/terraform/src/main/java/com/walmartlabs/concord/plugins/terraform/TerraformBinaryResolver.java
- tasks/terraform/src/main/java/com/walmartlabs/concord/plugins/terraform/TerraformTask.java
Refactor the current binary resolving code into `TerraformBinaryResolver`. The resolver looks for the binary using the following methods:
- looks for `${workDir}/.terraform/terraform` first;
- use `toolUrl` is specified;
- use a local binary from `$PATH` if `ignoreLocalBinary: false` (default);
- download the binary from the standard location using the default version or the version specified in `toolVersion`.
cc @jvanzyl
> terraform: option to use a local binary

- CHANGELOG.md
- pom.xml
- tasks/terraform/src/main/java/com/walmartlabs/concord/plugins/terraform/TerraformBinaryResolver.java
- tasks/terraform/src/main/java/com/walmartlabs/concord/plugins/terraform/TerraformTask.java
- tasks/terraform/src/main/java/com/walmartlabs/concord/plugins/terraform/TerraformTaskV2.java
- tasks/terraform/src/main/java/com/walmartlabs/concord/plugins/terraform/backend/ConcordV2Backend.java
Update the Terraform plugin after a breaking change in v2 SDK.
Fix the `toolUrl` usage - it was downloading the specified archive but not actually using its binary.
> terraform: update to Concord 1.63.0, fix logging, fix toolUrl

- CHANGELOG.md
- tasks/terraform/src/main/java/com/walmartlabs/concord/plugins/terraform/TerraformTaskV2.java
The v2 version of the task was incorrectly filling in the `hasChange` property in the result object.
> terraform: fix incorrect value of hasChanges property

- tasks/terraform/src/main/java/com/walmartlabs/concord/plugins/terraform/actions/ApplyAction.java
- tasks/terraform/src/main/java/com/walmartlabs/concord/plugins/terraform/actions/DestroyAction.java
- tasks/terraform/src/main/java/com/walmartlabs/concord/plugins/terraform/actions/PlanAction.java
- tasks/terraform/src/main/java/com/walmartlabs/concord/plugins/terraform/commands/ApplyCommand.java
Using `dir` and `extraVars` fails. TF is unable to find the `*.auto.tfvars.json` files generated by the plugin.
Test case:
```yaml
configuration:
dependencies:
- "mvn://com.walmartlabs.concord.plugins:terraform-task:1.32.2"
flows:
default:
- task: terraform
in:
verbose: true
debug: true
backend: "none"
action: apply
saveOutput: true
dir: "mydir"
extraVars:
region: "us-east-2"
```
```
// init.tf
terraform {
required_version = ">= 0.12"
}
provider "aws" {
region     = var.region
version    = "= 2.61.0"
}
variable "region" {
type = string
}
output "xyz" {
value = var.region
}
```
Running:
```
curl -ik -H 'Authorization: <token>' -F concord.yml=@concord.yml -F mydir/init.tf=@init.tf http://localhost:8001/api/v1/process
```
The current version (1.32.2) fails:
```
16:27:53 [INFO ] Saving …
```
> terraform: save .auto.tfvars.json files in $PWD

- tasks/terraform/README.md
- tasks/terraform/src/main/java/com/walmartlabs/concord/plugins/terraform/TaskConstants.java
- tasks/terraform/src/main/java/com/walmartlabs/concord/plugins/terraform/TerraformTask.java
- tasks/terraform/src/main/java/com/walmartlabs/concord/plugins/terraform/TerraformTaskCommon.java
- tasks/terraform/src/main/java/com/walmartlabs/concord/plugins/terraform/TerraformTaskV2.java
- tasks/terraform/src/main/java/com/walmartlabs/concord/plugins/terraform/actions/ApplyAction.java
- tasks/terraform/src/main/java/com/walmartlabs/concord/plugins/terraform/actions/DestroyAction.java
- tasks/terraform/src/main/java/com/walmartlabs/concord/plugins/terraform/actions/OutputAction.java
- tasks/terraform/src/main/java/com/walmartlabs/concord/plugins/terraform/actions/PlanAction.java
- tasks/terraform/src/main/java/com/walmartlabs/concord/plugins/terraform/backend/ConcordV1Backend.java
- tasks/terraform/src/main/java/com/walmartlabs/concord/plugins/terraform/backend/ConcordV2Backend.java
- tasks/terraform/src/main/java/com/walmartlabs/concord/plugins/terraform/commands/DestroyCommand.java
- tasks/terraform/src/test/java/com/walmartlabs/concord/plugins/terraform/TerraformTaskIT.java
- tasks/terraform/src/test/resources/com/walmartlabs/concord/plugins/terraform/runtimeV1/concord.yml
- tasks/terraform/src/test/resources/com/walmartlabs/concord/plugins/terraform/runtimeV2/concord.yml
Some Terraform configurations expect `terraform plan` (or `apply`) to
run in a specific directory (i.e. if the files use relative paths).
This change adds a way to override the binary's `$PWD`.
Docs: https://github.com/walmartlabs/concord-website/pull/57
> terraform: allow specifying the PWD

- tasks/ldap/src/main/java/com/walmartlabs/concord/plugins/ldap/LdapTaskCommon.java
- tasks/ldap/src/main/java/com/walmartlabs/concord/plugins/ldap/TaskParams.java
new input parameter for isMemeberOf and getGroup: 
`securityGroupTypes` - list of strings, optional, list of group types to validate a group being a secure type;
> ldap: security group types attribute

- tasks/git/src/main/java/com/walmartlabs/concord/plugins/git/GitHubTask.java
This change will help the clients of github task to know what is the default_branch of the repository.
> on the getCommit(), additionally fetch the repository's default_branch

- tasks/git/src/main/java/com/walmartlabs/concord/plugins/git/GitTask.java
- tasks/git/src/main/java/com/walmartlabs/concord/plugins/git/model/exception/RefNotFoundException.java
Returns the latest HEAD ref of the branch an action is performed on. Example response for `commitAndPush`:
```text
{
"changeList" : [ "new-file.txt" ],
"headSHA" : "95938259eadf6a32b7852bd230d8a8a70c5ef6da",
"ok" : true,
"error" : "",
"status" : "SUCCESS"
}
```
> git: Return HEAD SHA after performing action

- tasks/git/pom.xml
- tasks/git/src/main/java/com/walmartlabs/concord/plugins/git/GitTask.java
init repository with branch and empty commit:
```
- task: git
in:
action: init
url: https://github.com/brig/test.git
initBranch: test
workingDir: myRepo
- task: git
in:
action: commit
workingDir: myRepo
auth: "..."
baseBranch: "test"
allowEmptyCommit: true
commitMessage: "init message"
commitUsername: "brig"
commitEmail: "ybrigo@gmail.com"
pushChanges: true
```
> git: init action, empty commit, jgit version up

- tasks/terraform/src/main/java/com/walmartlabs/concord/plugins/terraform/TerraformTaskCommon.java
example from docs:
```
- task: terraform
in:
action: destroy
extraEnv: 
CONFIRM_DESTROY: 1
```
finished with exception:
```
18:04:16 [ERROR] main -> unhandled exception
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
at java.lang.ProcessEnvironment$StringEnvironment.put(ProcessEnvironment.java:221)
at java.util.AbstractMap.putAll(AbstractMap.java:281)
at com.walmartlabs.concord.plugins.terraform.Terraform.exec(Terraform.java:80)
at com.walmartlabs.concord.plugins.terraform.commands.InitCommand.exec(InitCommand.java:59)
at com.walmartlabs.concord.plugins.terraform.actions.Action.init(Action.java:137)
at com.walmartlabs.concord.plugins.terraform.actions.DestroyAction.exec(DestroyAction.java:50)
at …
```
> terraform: class cast exception fix

- tasks/taurus/pom.xml
This should be replaced with `DependencyManager` usage, but until then the build is broken because `5.2.1` is no longer published and this will fix it.
> taurus: update jmeter version to 5.5

- pom.xml
- tasks/terraform/README.md
- tasks/terraform/pom.xml
- tasks/terraform/src/main/java/com/walmartlabs/concord/plugins/terraform/TaskConstants.java
- tasks/terraform/src/main/java/com/walmartlabs/concord/plugins/terraform/Terraform.java
- tasks/terraform/src/main/java/com/walmartlabs/concord/plugins/terraform/TerraformArgs.java
- tasks/terraform/src/main/java/com/walmartlabs/concord/plugins/terraform/TerraformBinaryResolver.java
- tasks/terraform/src/main/java/com/walmartlabs/concord/plugins/terraform/TerraformDockerService.java
- tasks/terraform/src/main/java/com/walmartlabs/concord/plugins/terraform/TerraformExecutable.java
- tasks/terraform/src/main/java/com/walmartlabs/concord/plugins/terraform/TerraformTask.java
- tasks/terraform/src/main/java/com/walmartlabs/concord/plugins/terraform/TerraformTaskV2.java
- tasks/terraform/src/main/java/com/walmartlabs/concord/plugins/terraform/actions/PlanAction.java
- tasks/terraform/src/main/java/com/walmartlabs/concord/plugins/terraform/commands/ApplyCommand.java
- tasks/terraform/src/main/java/com/walmartlabs/concord/plugins/terraform/commands/DestroyCommand.java
- tasks/terraform/src/main/java/com/walmartlabs/concord/plugins/terraform/commands/InitCommand.java
- tasks/terraform/src/main/java/com/walmartlabs/concord/plugins/terraform/commands/OutputCommand.java
- tasks/terraform/src/main/java/com/walmartlabs/concord/plugins/terraform/commands/PlanCommand.java
- tasks/terraform/src/test/java/com/walmartlabs/concord/plugins/terraform/AbstractTerraformTest.java
- tasks/terraform/src/test/java/com/walmartlabs/concord/plugins/terraform/TerraformTaskTest.java
- tasks/terraform/src/test/java/com/walmartlabs/concord/plugins/terraform/TerraformTaskTestV2.java
- tasks/terraform/src/test/java/com/walmartlabs/concord/plugins/terraform/docker/DockerContainerSpecV1Compat.java
- tasks/terraform/src/test/java/com/walmartlabs/concord/plugins/terraform/docker/DockerService.java
- tasks/terraform/src/test/terraform/main.tf
- tasks/terraform/src/test/terraform/minimal_aws/main.tf
- tasks/terraform/src/test/terraform/minimal_azure/main.tf
- tasks/terraform/testPayload.sh
- tasks/terraform/testPayloadV1.yml
- tasks/terraform/testPayloadV2.yml
Initial support for executing terraform commands inside a docker container. Helpful for executing with dependencies (e.g. Azure CLI, large custom modules, etc) that are not reasonable to ship in the main Concord Agent container.
* Support for executing terraform in a docker container
* Fix https://github.com/walmartlabs/concord-plugins/issues/88
* Simpler [tasks/terraform/src/test/terraform/minimal_aws/main.tf](https://github.com/walmartlabs/concord-plugins/compare/tf-docker-exec?expand=1#diff-36b1c5d6b00d39ec45aa1be057b9bf66bd85f280fe6a9776083a12879a475382) for AWS testing (so we don't accidentally leave compute laying around after a failed test)
* More tests
> terraform: support for executing in a container

- tasks/akeyless/pom.xml
- tasks/akeyless/src/main/java/com/walmartlabs/concord/plugins/akeyless/AkeylessCommon.java
- tasks/akeyless/src/main/java/com/walmartlabs/concord/plugins/akeyless/model/SecretCache.java
- tasks/akeyless/src/main/java/com/walmartlabs/concord/plugins/akeyless/model/SecretCacheImpl.java
- tasks/akeyless/src/main/java/com/walmartlabs/concord/plugins/akeyless/model/SecretCacheNoop.java
- tasks/akeyless/src/main/java/com/walmartlabs/concord/plugins/akeyless/model/TaskParams.java
- tasks/akeyless/src/main/java/com/walmartlabs/concord/plugins/akeyless/model/TaskParamsImpl.java
- tasks/akeyless/src/test/java/com/walmartlabs/concord/plugins/akeyless/it/CommonIT.java
- tasks/akeyless/testPayloadV1.yml
- tasks/akeyless/testPayloadV2.yml
- tasks/akeyless/testV2.yml
New action `auth` can be used to obtain an access token.
New parameter `accessToken` can be used to directly provide the access token for calls. Otherwise, the task first generates one from the `auth` param and then uses it for the subsequent API call.
> akeyless: support direct usage of access token

- tasks/s3/pom.xml
- tasks/s3/src/test/java/com/walmartlabs/concord/plugins/s3/S3TaskTest.java
- tasks/s3/src/test/java/com/walmartlabs/concord/plugins/s3/S3TaskV2Test.java
- tasks/s3/src/test/resources/logback-test.xml
The transitive dependencies of `aws-java-sdk` are numerous and large, which causes process startup time to suffer dramatically when including the `s3` plugin. The plugin doesn't need the transitive dependencies.
- Exclude `aws-java-sdk` transitive deps. Reduces resolved deps from 264M to 5.9M.
- Update/add unit tests leveraging [testcontainers and S3Mock](https://github.com/adobe/S3Mock#start-using-testcontainers).
> s3: exclude unnecessary transitive dependencies

- tasks/argocd/pom.xml
- tasks/argocd/src/main/java/com/walmartlabs/concord/plugins/argocd/ArgoCdClient.java
- tasks/argocd/src/main/java/com/walmartlabs/concord/plugins/argocd/AzureAuthCache.java
- tasks/argocd/src/main/java/com/walmartlabs/concord/plugins/argocd/AzureAuthHandler.java
- tasks/argocd/src/main/java/com/walmartlabs/concord/plugins/argocd/TaskParams.java
- tasks/argocd/src/main/java/com/walmartlabs/concord/plugins/argocd/TaskParamsImpl.java
- tasks/argocd/src/test/java/com/walmartlabs/concord/plugins/argocd/ArgoCdClientTest.java
- tasks/argocd/src/test/java/com/walmartlabs/concord/plugins/argocd/TaskParamsImplTest.java
- tasks/argocd/src/test/resources/example-flow/concord.yml
```
configuration:
runtime: concord-v2
arguments:
defaults:
baseUrl: "http://argo.net"  # replace with actual url
auth:
azure:
clientId: <client_id>
authority: <authority>     #https://login.microsoftonline.com/<tenantId>/<Version>
scope:
- "user.read"
username: username@domain.com
password:  *****
```
> argocd: add support for azure ad auth

- tasks/ldap/src/main/java/com/walmartlabs/concord/plugins/ldap/LdapConnectionCfg.java
- tasks/ldap/src/main/java/com/walmartlabs/concord/plugins/ldap/LdapTask.java
- tasks/ldap/src/main/java/com/walmartlabs/concord/plugins/ldap/LdapTaskCommon.java
- tasks/ldap/src/main/java/com/walmartlabs/concord/plugins/ldap/TaskParams.java
- tasks/ldap/src/main/java/com/walmartlabs/concord/plugins/ldap/v2/LdapTaskV2.java
```
configuration:
runtime: concord-v2
...
arguments:
ldapParams:
dnsSrvRr: 
name: "_ldap._tcp.domain.com"
protocol: "ldaps"
port: "3269"
```
* added support for `ldapParams` in v2
* cleaned up duplicate retries
> ldap-task: support for dns SRV resource record

- tasks/argocd/src/main/java/com/walmartlabs/concord/plugins/argocd/ArgoCdConstants.java
- tasks/argocd/src/main/java/com/walmartlabs/concord/plugins/argocd/ObjectMapper.java
- tasks/argocd/src/main/java/com/walmartlabs/concord/plugins/argocd/TaskParams.java
- tasks/argocd/src/main/java/com/walmartlabs/concord/plugins/argocd/TaskParamsImpl.java
`spec` option where users can specify additional options (not available as task parameters) as part of ArgoCD application creation. 
NOTE: 
1. if any of the mandatory task parameters are also defined as part of the `spec` parameter, they will be overridden by the values provided by the task parameters. 
2. Optional Task parameters could be skipped and provided as part of the `spec` parameter itself. But if they are defined in both places, the values provided as part of the task parameters will be given preference over the values provided for the same parameters as part of the spec.
Examples:
1. Using kustomize instead of helm
```
flows:
default:
- task: argocd
in:
action: create
app: test-app
gitRepo:
repoUrl: https://github.com/myorg/myrepo.git
targetRevision: HEAD
path: test
project: …
```
> argocd: optional `spec` option to provide additional params for app creation

- tasks/argocd/src/main/java/com/walmartlabs/concord/plugins/argocd/ArgoCdClient.java
- tasks/argocd/src/main/java/com/walmartlabs/concord/plugins/argocd/ArgoCdTask.java
- tasks/argocd/src/main/java/com/walmartlabs/concord/plugins/argocd/CallRetry.java
- tasks/argocd/src/main/java/com/walmartlabs/concord/plugins/argocd/TaskParams.java
- tasks/argocd/src/main/java/com/walmartlabs/concord/plugins/argocd/TaskParamsImpl.java
- tasks/argocd/src/test/java/com/walmartlabs/concord/plugins/argocd/CallRetryTest.java
- tasks/argocd/src/test/java/com/walmartlabs/concord/plugins/argocd/TaskParamsImplTest.java
* Add options waitForSync,syncTimeout,watchHealth parameters for UpdateSpec and CreateUpdate operations
* Fixed timeout issues for waitForSync method by moving BuffereReader instance creation statement from try-with-resource block.
> argocd: new params for UpdateSpec and CreateUpdate actions. fix timeout issues

- pom.xml
- tasks/aws/examples/ecr/concord.yml
- tasks/aws/pom.xml
- tasks/aws/src/main/java/com/walmartlabs/concord/plugins/aws/EcrTask.java
- tasks/aws/src/test/java/com/walmartlabs/concord/plugins/aws/EcrTaskTest.java
- tasks/aws/src/test/resources/logback.xml
Running tasks/aws/examples/ecr/concord.yml:
```
> concord run
Starting...
15:07:33.142 [main] Image Details: [ {
"registryId" : "742982124480",
"repositoryName" : "foo",
"imageDigest" : "sha256:c49527020d9f72c711eb9ec89ae6162ddd88abebb69b79967c72b1ac56b60769",
"imageTags" : [ "latest" ],
"imageSizeInBytes" : 153448492,
"imagePushedAt" : 1718737639.000000000,
"imageScanStatus" : null,
"imageScanFindingsSummary" : null,
"imageManifestMediaType" : "application/vnd.docker.distribution.manifest.v2+json",
"artifactMediaType" : "application/vnd.docker.container.image.v1+json",
"lastRecordedPullTime" : null
} ]
...done!
```
> aws: add a basic ecr describe-images wrapper

- tasks/git/pom.xml
- tasks/git/src/test/java/com/walmartlabs/concord/plugins/git/GitHubCommonTest.java
Gson _should_ be a transitive dependency of `org.eclipse.egit.github.core`. I don't know why that's not true in practice. Since concord-client2 doesn't include gson anymore, this task now need to have it explicitly defined.
> git: add gson to pom for egit support

- tasks/terraform/pom.xml
- tasks/terraform/src/test/java/com/walmartlabs/concord/plugins/terraform/AbstractTerraformTest.java
- tasks/terraform/src/test/java/com/walmartlabs/concord/plugins/terraform/TerraformTaskIT.java
- tasks/terraform/src/test/java/com/walmartlabs/concord/plugins/terraform/TerraformTaskV2Test.java
okhttp is only used in the (disabled) unit tests. This replaces the download manager backed with the native `HttpClient`.
> terraform: remove okhttp dependency

- tasks/jira/pom.xml
- tasks/jira/src/main/java/com/walmartlabs/concord/plugins/jira/Constants.java
- tasks/jira/src/main/java/com/walmartlabs/concord/plugins/jira/JiraClient.java
- tasks/jira/src/main/java/com/walmartlabs/concord/plugins/jira/JiraClientCfg.java
- tasks/jira/src/main/java/com/walmartlabs/concord/plugins/jira/JiraHttpClient.java
- tasks/jira/src/main/java/com/walmartlabs/concord/plugins/jira/JiraHttpClientFactory.java
- tasks/jira/src/main/java/com/walmartlabs/concord/plugins/jira/JiraTask.java
- tasks/jira/src/main/java/com/walmartlabs/concord/plugins/jira/JiraTaskCommon.java
- tasks/jira/src/main/java/com/walmartlabs/concord/plugins/jira/NativeJiraHttpClient.java
- tasks/jira/src/main/java/com/walmartlabs/concord/plugins/jira/TaskParams.java
- tasks/jira/src/main/java/com/walmartlabs/concord/plugins/jira/v2/JiraTaskV2.java
- tasks/jira/src/test/java/com/walmartlabs/concord/plugins/jira/AbstractWiremockTest.java
- tasks/jira/src/test/java/com/walmartlabs/concord/plugins/jira/CommonClientLoaderTest.java
- tasks/jira/src/test/java/com/walmartlabs/concord/plugins/jira/CommonTest.java
- tasks/jira/src/test/java/com/walmartlabs/concord/plugins/jira/JiraClientTest.java
- tasks/jira/src/test/java/com/walmartlabs/concord/plugins/jira/JiraTaskTest.java
- tasks/jira/src/test/java/com/walmartlabs/concord/plugins/jira/NativeJiraHttpClientTest.java
- tasks/jira/src/test/java/com/walmartlabs/concord/plugins/jira/TaskParamsTest.java
- tasks/jira/src/test/java/com/walmartlabs/concord/plugins/jira/v2/JiraTaskV2Test.java
* not sure why unit tests were disabled, but now they back and improved
* add new jira http client using native `HttpClient`
* leverages concord-client2 for `POST multipart/form-data` call
* falls back to okhttp for now, until 2.10.0+ is more widespread
* Remove Gson dependency in favor of provided jackson
> jira: enable tests, remove Gson usage, prep for okhttp 2.X removal

- pom.xml
- runtime/opentelemetry/pom.xml
- tasks/argocd/pom.xml
- tasks/aws/pom.xml
- tasks/confluence/pom.xml
- tasks/git/pom.xml
- tasks/gremlin/pom.xml
- tasks/jenkins/pom.xml
- tasks/jira/pom.xml
- tasks/jsonpath/pom.xml
- tasks/ldap/pom.xml
- tasks/msteams/pom.xml
- tasks/packer/pom.xml
- tasks/s3/pom.xml
- tasks/terraform/pom.xml
- tasks/xml/pom.xml
- tasks/zoom/pom.xml
concord-maven-plugin: https://github.com/concord-workflow/concord-maven-plugin
A simple plugin that checks runtime and plugin dependency versions, ensuring runtime dependencies are marked as provided in the plugin. Currently, it doesn’t handle transitive dependencies
all tasks updated except `akeyless`:
```
[INFO] --- concord:0.0.29:verify (default) @ akeyless-task ---
[INFO] Resolving runtime-v2 dependencies for version '2.19.0'
[WARNING] The dependency 'com.fasterxml.jackson.core:jackson-core:2.13.3 (compile)' has an invalid version.
Expected version: '2.17.0'. Please update your POM.
[WARNING] The dependency 'com.fasterxml.jackson.core:jackson-annotations:2.13.3 (compile)' has an invalid version.
Expected version: '2.17.0'. Please update your POM.
[WARNING] The dependency …
```
> project: use concord maven plugin

- tasks/jira/src/main/java/com/walmartlabs/concord/plugins/jira/JiraTaskCommon.java
issuePriority is optional in code:
```
public String issuePriority() {
return variables.getString(JIRA_ISSUE_PRIORITY_KEY, null);
}
```
> jira-task: properly handle issue creation when no priority is specified

- pom.xml
- runtime/codecoverage/README.md
- runtime/codecoverage/pom.xml
- runtime/codecoverage/src/main/java/com/walmartlabs/concord/plugins/codecoverage/CodeCoverage.java
- runtime/codecoverage/src/main/java/com/walmartlabs/concord/plugins/codecoverage/CodecoverageModule.java
- runtime/codecoverage/src/main/java/com/walmartlabs/concord/plugins/codecoverage/LcovReportProducer.java
- runtime/codecoverage/src/main/java/com/walmartlabs/concord/plugins/codecoverage/StepInfo.java
- runtime/codecoverage/src/main/java/com/walmartlabs/concord/plugins/codecoverage/StepsRecorder.java
- runtime/codecoverage/src/test/resources/gen_html.bash
> code coverage runtime plugin

- tasks/git/src/main/java/com/walmartlabs/concord/plugins/git/GitHubTask.java
as a result, it will be possible to run in dry-run mode without making any changes:
```
...
- task: github
in:
action: createPr
out: createResponse
- task: github
in:
action: closePr/mergePr/whatever  
prId: "${createResponse.prId}"
...
```
> github: return `fake` PR ID in dry-run-mode for craeatePr action

- tasks/git/src/main/java/com/walmartlabs/concord/plugins/git/GitHubTask.java
before:
```
...
out:
commit: "${result.result.data}"
```
after:
```
...
out:
commit: "${result.commit}"
```
> github: simplify result for getCommit action
